config/routes.rb
Helloworld::Application.routes.draw do |map|
  map.resources :profiles

  get "auth/login"
  get "auth/logout"
  get "auth/register"
  map.register_user 'auth/register_user', :controller => 'auth', :action => 'register_user'
  map.authenticate "auth/authenticate", :controller => 'auth', :action => 'authenticate'

  match 'home' => 'home#dashboard', :as => :dashboard
  match 'home/messages' => 'home#messages', :as => :messages
  match 'home/contacts' => 'home#contacts', :as => :contacts
  match 'home/profile' => 'home#profile', :as => :myprofile
  match 'home/about' => 'home#about', :as => :about


  match 'public/:id(.:format)' => 'profiles#show_public'

end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :from, :class_name => "Profile"
  belongs_to :to, :class_name => "Profile"
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  belongs_to :private_address, :class_name => 'Address'
  belongs_to :business_address, :class_name => 'Address'
  has_many :profile_attributes
  has_many :relations, :foreign_key => :source_id
  #has_many :contacts, :through => :relations, :source => :destination
  has_many :sent_messages, :foreign_key => :from_id, :class_name => "Message"
  has_many :received_messages, :foreign_key => :to_id, :class_name => "Message"
  has_many :statuses

  def full_name 
    "#{first_name} #{last_name}"
  end

  def contact_count 
    # intentionally stupid
    contacts.count
  end

  def message_count
    received_messages.count
  end

  def contacts
    Relation.joins(:destination).where(:source_id => id)
  end

  def image
    "user.png"
  end
end

app/models/profile_attribute.rb
class ProfileAttribute < ActiveRecord::Base
  def self.types 
    ["work", "home", "alternate"]
  end
end

app/models/relation.rb
class Relation < ActiveRecord::Base
  belongs_to :source, :class_name => "Profile"
  belongs_to :destination, :class_name => "Profile"
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :profile
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
  
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  # Note: this implementation is a security nightmare 
  # and NOT intended for production use.

  def random_user
    User.find(:first, :offset => rand(User.count))
  end

  def login
    @user = User.new
    @dest ||= dashboard_path
    sample_user = random_user
    @hint = "Try user '#{sample_user.login}' with password '#{sample_user.password}' to get started."
  end

  def authenticate
    @user = User.find_by_login(params[:user][:login])
    if @user and @user.password == params[:user][:password]
      session[:user] = @user.id
      dest = params[:dest] || dashboard_path
      redirect_to dest
    else
      flash[:notice] = "Wrong username/password combination"
      redirect_to :action => :login
    end
  end

  def logout
    session.delete(:user)
  end

  def register
    @user = User.new
  end

  def register_user
    @user = User.find_by_login(params[:user][:login])
    if @user.nil?
      @user = User.create(params[:user])
      session[:user] = @user.id
      dest = params[:dest] || home_path
      redirect_to dest
    else
      flash[:notice] = "Could not create user - user name already taken"
      redirect_to :action => :register
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'
  before_filter :setup_context

  def dashboard
  end

  def messages
    @messages = Message.where(:to_id => @profile.id).paginate :page => params[:page], 
                                                           :per_page => 5,
                                                           :order => 'updated_at DESC'
  end

  def contacts
    @contacts = @profile.contacts.paginate :page => params[:page], 
                                           :per_page => 5,
                                           :order => 'updated_at DESC'
  end

  def setup_context
    @user = session[:user].nil? ? nil : User.find(session[:user])
    if @user.nil?
      redirect_to :controller => 'auth', :action => 'login'
    else
      @profile = @user.profile || @user.create_profile
      @contact_count = @profile.contact_count
      @message_count = @profile.message_count
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate, :only => 'admin'
  respond_to :html, :json

  def show_public
    @profile = Profile.find(params[:id])
    respond_with @profile
  end

  def show
    @profile = Profile.find(params[:id])
    @contacts = @profile.contacts
    respond_with @profile
  end

  def admin
  end

  def logout
    render(:status => 401)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/_contact.html.erb
<% content_tag_for(:li, contact) do %>
<p class="name"><%= link_to(contact.full_name, contact) %></p>
<p class="company"><span class="label">Company:</span><%= contact.company %></p>
<% end %>

app/views/home/_footer.html.erb
	<div id="footer">
	  <a href="#" title="">This is a sample application. Copyright innoQ 2010</a>
	</div>

app/views/home/_header.html.erb
		<div id="header">
		
			<div id="logo">
				<img src="images/logo.png" alt="Logo" />		
			</div>
			<!-- /logo -->
			
			<div id="claim">
				<img src="images/claim.png" alt="Hello World" />		
			</div>
			<!-- /logo -->
			
			<div id="meta">
			  <ul>
			    <li><%= link_to "Logout", :controller => 'auth', :action => 'logout' %></li>
			    <li><a href="">Imprint</a></li>
			    <li><a href="">About</a></li>
			  </ul>
			</div>
			<!-- /meta -->
			
			<div id="search">
				
			</div>
			<!-- /search -->
			
			<ul id="menu">
			  <li><%= link_to "Dashboard", dashboard_path, :class => "first" %></li>
			  <li><%= link_to "Messages (#{@message_count})", messages_path %></li>
			  <li><%= link_to "Contacts", contacts_path %></li>
			  <li><%= link_to "Profile", myprofile_path %></li>
			  <li><%= link_to "About", about_path, :class => "last" %></li>
        		</ul>
			<!-- /menu -->
			
				
		</div>	
		<!-- /header -->
		
		
		
		
		

app/views/home/_status.html.erb
<div class="profile-stream-item">
  <span class="profile-stream-item-date"><%= @status.created_at %></span>
  <%= @status.message %>
</div>

app/views/home/about.html.erb
<p>A lot of descriptive text about this sample application</p>

app/views/home/contacts.html.erb
<ul id="contact-list">
<%= render :partial => "contact", :collection => @contacts %>
</ul> 

app/views/home/dashboard.html.erb
			<h1>Profile</h1>
		
			<div id="col-one">
				
				<div class="profile-image">
				<img src='<%= image_path(@profile.image) %>'  />
				</div>
				<!-- /profile-image -->
				
				<div class="profile-actions">
					<a href="#" title="">&raquo; Upload new image</a>
					<a href="#" title="">&raquo; Edit profile</a>
				</div>
				<!-- /profile-actions -->
				
				<h2>User's profile updates (<%= @profile.statuses.count %>)</h2>
					
				<div class="profile-stream">
				  <%= render :partial => 'status', :collection => @profile.statuses %>
				</div>
				<!-- /profile-stream -->
				
			</div>
			<!-- /col-one -->
			
			<div id="col-two">
				<div class="profile-center">
					
					<h3><%= @profile.full_name %></h3>
					<p>UserTitle</p>
					
					<div class="profile-center-company">
						<strong>Company Name</strong><br />
						Street 4001<br />
						1000 Cityname
					</div>
					
					<h4>About Me</h4>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.</p>
					
					<h4>Contact Data</h4>
    <%= yield %>
					
					<div class="profile-center-contact-label">Telephone</div>
					<div class="profile-center-contact-data">0241 400 85 662</div>
					<div class="clear"></div>
					<!-- /item -->
					<div class="profile-center-contact-label">Telephone</div>
					<div class="profile-center-contact-data">0241 400 85 662</div>
					<div class="clear"></div>
					<!-- /item -->
					<div class="profile-center-contact-label">Telephone</div>
					<div class="profile-center-contact-data">0241 400 85 662</div>
					<div class="clear"></div>
					<!-- /item -->
					<div class="profile-center-contact-label">Telephone</div>
					<div class="profile-center-contact-data">0241 400 85 662</div>
					<div class="clear"></div>
					<!-- /item -->
					<div class="profile-center-contact-label">Telephone</div>
					<div class="profile-center-contact-data">0241 400 85 662</div>
					<div class="clear"></div>
					<!-- /item -->
					
				</div>
				
				<a href="#" title="" class="button-blue">Send Message</a>
				
			</div>
			<!-- /col-two -->
			
			<div id="col-three">
				
				<h2>User's contacts (<%= @contact_count %>)</h2>
				
				<div class="contact-list-small">
				

					<div class="contact-list-small-item">
						<div class="contact-list-small-img">
							<a href="#" title=""><img src="img/user-small.jpg" alt="user-small" width="61" height="61" /></a>					
						</div>
						<div class="contact-list-small-text">
							<div class="contact-list-small-username">Mandy Nuss</div>
							<div class="contact-list-small-title">CEO LUSTIG AG</div>
							<div class="contact-list-small-email"><a href="#" title="mailto:test@test.de">test@test.de</a></div>
						</div>
						<div class="clear"><!-- clear --></div>
					</div>
					<!-- /contact-list-small-item -->
					<div class="contact-list-small-item">
						<div class="contact-list-small-img">
							<a href="#" title=""><img src="img/user-small.jpg" alt="user-small" width="61" height="61" /></a>					
						</div>
						<div class="contact-list-small-text">
							<div class="contact-list-small-username">Mandy Nuss</div>
							<div class="contact-list-small-title">CEO LUSTIG AG</div>
							<div class="contact-list-small-email"><a href="#" title="mailto:test@test.de">test@test.de</a></div>
						</div>
						<div class="clear"><!-- clear --></div>
					</div>
					<!-- /contact-list-small-item -->
					<div class="contact-list-small-item">
						<div class="contact-list-small-img">
							<a href="#" title=""><img src="img/user-small.jpg" alt="user-small" width="61" height="61" /></a>					
						</div>
						<div class="contact-list-small-text">
							<div class="contact-list-small-username">Mandy Nuss</div>
							<div class="contact-list-small-title">CEO LUSTIG AG</div>
							<div class="contact-list-small-email"><a href="#" title="mailto:test@test.de">test@test.de</a></div>
						</div>
						<div class="clear"><!-- clear --></div>
					</div>
					<!-- /contact-list-small-item -->
				
				
				</div>
				<!-- /contact-list-small -->
			</div>
			<!-- /col-three -->
			
			<div class="clear"><!-- clear --></div>
			






<!--<p class="message-count"><span class="label"># of --
  --Messages:</span><%= @message_count %></p> -->

app/views/home/messages.html.erb
<p>Messages: <%= @messages.count %>
<ul>
<% @messages.each do |m| %>
  <% content_tag_for(:li, m) do %>
  <p class="from"><span class="label">From:</span><%= link_to(m.from.full_name, m.from) %></p>
  <p class="subject"><span class="label">Subject:</span><%= m.subject %></p>
  <% end %>
<% end %>
<%= will_paginate @messages %>
</ul>

app/views/home/profile.html.erb
<% div_for @profile do %>
<p class="profession"><span class="label">Profession:</span><%= @profile.profession %></p>
<p class="company"><span class="label">Company:</span><%= @profile.company %></p>
<p class="about"><span class="label">About <%= @profile.first_name %>:</span><%= @profile.about %></p>
<p class="created-at"><span class="label">Created:</span><%= @profile.created_at %></p>
<p class="updated-at"><span class="label">Updated:</span><%= @profile.updated_at %></p>
<p class="contact-count"><span class="label"># of Contacts:</span><%= @profile.contact_count %></p>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helloworld</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="de">
	
<head>
	
  <title>[TITLE]</title>
	<link rel="stylesheet" href="stylesheets/reset.css" type="text/css" media="screen" title="default" />
	<link rel="stylesheet" href="stylesheets/main.css" type="text/css" media="screen" title="default" />
	<link rel="stylesheet" href="stylesheets/dropdown.css" type="text/css" media="screen" title="default" />
  <!--<%= stylesheet_link_tag :all %>-->
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
 	<!-- css -->
	
	<!-- override for IE-->
	
  	<!--[if IE 6]>
	<style type="text/css" media="all">@import "css/ie6.css";</style>
  	<![endif]-->
  	
  	<!--[if IE 7]>
        <style type="text/css" media="all">@import "css/ie7.css";</style>
        <![endif]-->
	
	<!-- scripts -->
	<script type="text/javascript" src="js/main.js"></script>
	
</head>
<body>
  <a name="tothetop"></a>
  <div id="main">
<%= render :partial => 'header' %>

		<div id="content-holder">
		  <%= yield %>
		</div>
		<!-- /content-holder -->
  </div>
  <!-- /main -->
	

<%= render :partial => 'footer' %>

  </body>
</html>

app/views/profiles/show.html.erb
<% div_for @profile do %>
<h2><%= @profile.full_name %>'s Public Profile</h2>
<p class="login_comment">If you were logged in, you could see a lot more! Login or register.</p>
<p class="profession"><span class="label">Profession:</span><%= @profile.profession %></p>
<p class="company"><span class="label">Company:</span><%= @profile.company %></p>
<p class="about"><span class="label">About <%= @profile.first_name %>:</span><%= @profile.about %></p>
<p class="created-at"><span class="label">Member since:</span><%= @profile.created_at %></p>
<p class="contact-count"><span class="label"># of Contacts:</span><%= @profile.contact_count %></p>
<% end %>

app/views/profiles/show_public.html.erb
<% div_for @profile do %>
<h2><%= @profile.full_name %>'s Public Profile</h2>
<p class="login_comment">If you were logged in, you could see a lot more! Login or register.</p>
<p class="profession"><span class="label">Profession:</span><%= @profile.profession %></p>
<p class="company"><span class="label">Company:</span><%= @profile.company %></p>
<p class="about"><span class="label">About <%= @profile.first_name %>:</span><%= @profile.about %></p>
<p class="created-at"><span class="label">Member since:</span><%= @profile.created_at %></p>
<p class="contact-count"><span class="label"># of Contacts:</span><%= @profile.contact_count %></p>
<% end %>